---
namespace: "serdigital64"
name: "database"
version: "2.1.4"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating database tools provisioning."
license:
  - "Apache-2.0"
tags:
  - "database"
dependencies:
  serdigital64.system: "*"
repository: "https://github.com/aplatform64/aplatform64"
homepage: "https://github.com/aplatform64/aplatform64"
issues: "https://github.com/aplatform64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
